- name: Include distribution specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - default.yml
      paths:
        - vars
  tags:
    - always
    - fail2ban

- include_tasks: "install-{{ ansible_facts.os_family }}.yml"
  tags:
    - fail2ban

- name: Copy jail files
  template:
    src: "{{ item }}"
    dest: "{{ fail2ban_jail_path }}"
    owner: root
    group: root
    mode: '0644'
  with_fileglob: jailfiles/*
  notify: restart fail2ban
  tags:
    - fail2ban

- name: Start and enable fail2ban service
  service:
    name: fail2ban
    state: started
    enabled: yes
  tags:
    - fail2ban
