- name: Include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - main.yml
  tags:
    - always
    - fail2ban

- include_tasks: "install-{{ ansible_os_family }}.yml"
  tags:
    - fail2ban

- name: Copy jail files
  template:
    src: "{{ item }}"
    dest: "{{ fail2ban_jail_path }}"
    owner: root
    group: root
    mode: 0644
  with_fileglob: jailfiles/*
  notify: restart fail2ban
  tags:
    - fail2ban

- name: Start and enable fail2ban service
  service:
    name: fail2ban
    state: started
    enabled: true
  tags:
    - fail2ban
