Vagrant.configure(2) do |config|

  # config.dns.tld = "vagrant.dev"

  # CentOS 6
  config.vm.define "fail2ban-centos6" do |centos6|
    centos6.vm.box = "samdoran/centos6"
    centos6.vm.hostname = "fail2ban-centos6"
    centos6.vm.network "private_network", ip: "10.77.19.100"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "fail2ban-centos6"
      vbox.cpus = 1
      vbox.memory = 128
    end
  end

  # CentOS 7
  config.vm.define "fail2ban-centos7" do |centos7|
    centos7.vm.box = "samdoran/centos7"
    centos7.vm.hostname = "fail2ban-centos7"
    centos7.vm.network "private_network", ip: "10.77.19.101"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "fail2ban-el7"
      vbox.cpus = 1
      vbox.memory = 128
    end
  end

  # Ubuntu 12.04
  config.vm.define "fail2ban-ub12" do |ub12|
    ub12.vm.box = "geerlingguy/ubuntu1204"
    ub12.vm.hostname = "fail2ban-ub12"
    ub12.vm.network "private_network", ip: "10.77.19.102"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "fail2ban-ub12"
      vbox.cpus = 1
      vbox.memory = 128
    end
  end

  # Ubuntu 14.04
  config.vm.define "fail2ban-ub14" do |ub14|
    ub14.vm.box = "geerlingguy/ubuntu1404"
    ub14.vm.hostname = "fail2ban-ub14"
    ub14.vm.network "private_network", ip: "10.77.19.103"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "fail2ban-ub14"
      vbox.cpus = 1
      vbox.memory = 256
    end
  end

  # Ubuntu 16.04
  config.vm.define "fail2ban-ub16" do |ub16|
    ub16.vm.box = "geerlingguy/ubuntu1604"
    ub16.vm.hostname = "fail2ban-ub16"
    ub16.vm.network "private_network", ip: "10.77.19.104"
    ub16.vm.provider "virtualbox" do |vbox|
      vbox.name = "fail2ban-ub16"
      vbox.cpus = 1
      vbox.memory = 128
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
  end

end
